/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:144c7880-a802-46a1-99fb-1e0cecabb891",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_rVeKXggtL",
    "aws_user_pools_web_client_id": "2ejrml6l3ikdfu8ee219n9bc6r",
    "oauth": {}
};


export default awsmobile;
